"""Add attendance_all table

Revision ID: 05bf0c508adc
Revises: e4bb0bf2b3e3
Create Date: 2024-12-11 08:19:28.787672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bf0c508adc'
down_revision: Union[str, None] = 'e4bb0bf2b3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_all',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('in_out_mode', sa.Integer(), nullable=False),
    sa.Column('verify_mode', sa.Integer(), nullable=False),
    sa.Column('work_code', sa.Integer(), nullable=False),
    sa.Column('is_sync', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_all_id'), 'attendance_all', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_all_id'), table_name='attendance_all')
    op.drop_table('attendance_all')
    # ### end Alembic commands ###
