"""add_is_main_to_terminal

Revision ID: 134dc2cd702e
Revises: dad404ad3881
Create Date: 2024-12-06 11:42:19.197795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134dc2cd702e'
down_revision: Union[str, None] = 'dad404ad3881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminals', sa.Column('is_main', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminals', 'is_main')
    # ### end Alembic commands ###
