"""change_attendancess_is_sync

Revision ID: 97708ad25227
Revises: 00eeeb34878f
Create Date: 2024-12-11 13:05:12.298264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97708ad25227'
down_revision: Union[str, None] = '00eeeb34878f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_logs', sa.Column('is_sync', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_logs', 'is_sync')
    # ### end Alembic commands ###
