"""extend password field

Revision ID: acdfe8be49ef
Revises: 134dc2cd702e
Create Date: 2024-12-06 20:38:39.492553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdfe8be49ef'
down_revision: Union[str, None] = '134dc2cd702e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'password',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###
